### ISSUE TITLE
Nice work!  ETA on UDTs & Arrays?

### ISSUE THREAD

**Issue by skykep** [SerafinTech/ST-node-ethernet-ip#12]
Great improvement from the original fork.  I'm wondering if you have an idea of when UDTs & arrays will be included?

**Comment by SerafinTech** [comment]
Latest commit does UDTS and Arrays and Arrays of UDTs! Auto reconnect on PLC connection loss / power cycle.

**Comment by skykep** [comment]
Very cool.  Nice work!
