### ISSUE TITLE
Array of UDDT's with ControllerManager

### ISSUE THREAD

**Issue by srebling** [SerafinTech/ST-node-ethernet-ip#32]
How do you reference an element of an array of UUDT's using the ControllerManager addTag() function?
## Current Behavior
This example code from the README works fine for a single integer tag.
```
const {ControllerManager} = require('st-ethernet-ip')

const cm = new ControllerManager();

//addController(ipAddress, slot = 0, rpi = 100, connected = true, retrySP = 3000, opts = {})
const cont = cm.addController('192.168.86.200');

cont.connect();

//addTag(tagname, program = null, arrayDims = 0, arraySize = 0x01)
cont.addTag('TheInteger')

cont.on('TagChanged', (tag, prevValue) => {
  console.log(tag.name, ' changed from ', prevValue, ' => ', tag.value)
})

cont.on('error', (e) => {
  console.log(e)
})
```

## Expected Behavior
What is the correct syntax for adding a tag which is an element of a UDDT (or atomic) array.
`cont.addTag(?????)`
## Possible Solution (Optional)
Is it something similar to:
`cont.addTag(tagname, program = null, arrayDims = 0, arraySize = 0x01)`
I have not has success with that other than getting the first element only.

## Context
Ultimately I want to use this with your node-red node (node-red-contrib-cip-st-ethernet-ip).

## Your Environment

* Package version (Use `npm list` - e.g. *1.0.6*): 2.5.0
* Node Version (Use `node --version` - e.g. *9.8.0*): 16.14.2
* Operating System and version: OSX 10.15.7
* Controller Type (eg 1756-L83E/B): 1769-L24ER-QB1B CompactLogix 5370
* Controller Firmware (eg 30.11): 30.011

**Comment by SerafinTech** [comment]
Thanks for issue.  I just fixed the UDT array issue with the last commit. Install latest version!

To access an array element

```javascript
// Where n is the array index
cont.addTag('tagName[n]')
```
