### ISSUE TITLE
scan_rate failing at 2800 ms.

### ISSUE THREAD

**Issue by flacohenao** [SerafinTech/ST-node-ethernet-ip#43]
So, here I found a strange behavior and also I want to suggest one enhancement.

Whenever you create an `ExtController` you can also define the `scan_rate `trough the `rpi `parameter which by default is 100.

The deal with the `connect()` function is that you are assuming that the consumer want to scan the controller for the previously created `Tags` and add the `event_emitters `to them to instantly emit the events on the tags. This is very nice, but what about if I dont want to inmediately scan the variables in order to controll the reading in a more granular way.

One example to give you is: If I want to do a controller read on demand to a `TagGroup` I'd like to do it without loosing all this great features that you are already exposing... like the reconnecting and managing in a more abstract way the controllers instead of use the basic `Controller`.
Yet, this can be done, on demand, but still there is an ongoing background process happening due to "un asked" scans and emitting events on tags which possible I dont want to listen.

![image](https://github.com/SerafinTech/ST-node-ethernet-ip/assets/10132006/95709db8-e335-42fd-bd12-5948c388fd09)

This abstraction is great, but we can create two different functions or allow the `scan `and the `addTagEvents` at will. This will ensure performance and not wasting resources when we dont want to listen the events of the tags.

Now.. moving on the next topic... I found that when we increate the `rpi` for the scan rate above 2800ms, this error is thrown:

![image](https://github.com/SerafinTech/ST-node-ethernet-ip/assets/10132006/4165caf5-753a-42b0-af43-72bcf4e1e78d)

and this dont tell us much.. but in anycase, there are specific scenariosn in which I dont want to constanlty read on the PLC (like the one I told you, I want some screenshot of the values and not interested on `changed` evfents)

Thanks in advance to read... I hope we can support this feature.

**Comment by SerafinTech** [comment]
with a slow scan rate you would want to use unconnected messaging. 

```javascript
// For Controller class
let controller = new Controller(false);

//For extController class
let controller = new extController(ipaddress, slot, rpi, false)
```


If you don't  constantly communicate with a connected messaging controller, it will drop connection.

 For custom controller setup. use the original Controller class. The controller manager was a easy to use class for standard HMI type applications
