### ISSUE TITLE
Add LGX String support

### ISSUE THREAD

**Issue by radrevere** [SerafinTech/ST-node-ethernet-ip#54]
I realize that you are working on String support but I it looks like the README was last update 2 years ago and string support still isn't there.  I work more with PLC's that utilize the LGX style of tags and I noticed that the LGX string is a STRUCT and has the same value as your STRUCT define (0x02a0).  It's name, however, is "String" and its handle is 4060 when you grab the UDT information.  Anyways, we rarely use any UDT's other than the string and so I would like to propose a temporary solution to support the String type which can then potentially be utilized for the future UDT support (I have some ideas there).
1. Add "LGXSTR: 0x02a0" to your types in cip/data-types/index.js file (or replace STRUCT with LGXSTR for now)
2. under tag/index.js edit 2 functions, "parseReadMessageResponseValueForAtomic" and "generateWriteMessageRequestForAtomic"
- in both cases add LGXSTR to the types at the top of the function
3. Add the following to the "parseReadMessageResponseValueForAtomic" switch statement:
```
case LGXSTR: // struct for string
                var len = data.readUInt32LE(4);
                var tmp = ""; 
                // build string here so controller_value doesn't fire too many
                // OnChange events for those subscribed to changes
                // or use a different converstion method
                for(var i = 0; i < len; i++)
                {
                    // LGX string header = 8 bytes 
                    tmp += String.fromCharCode(data[8+i]);
                }
                this.controller_value = tmp;
                break;
```
4. Add the following to the "generateWriteMessageRequestForAtomic" switch statement:
```
case LGXSTR: // LGX string
                // override size with struct handle in header
                buf.writeUint16LE(0x0FCE,2);

                // string struct is a total of 90 by default
                var header = Buffer.alloc(6);
                header.writeInt16LE(1); // writing only one string
                header.writeInt32LE(tag.value.length,2); // length of string
                valBuf = Buffer.alloc(84); // standard string length
                valBuf.write(tag.value);

                buf = Buffer.concat([buf,header,valBuf]);
                break;
```

I have been testing this without any issues thus far. What I don't know is the impact it may have on reading other UDT's and so other checks will likely need to be added to avoid issues.  Not sure where it's stored but if you had the handle from an initial read you could thrown an exception or exit with an error if the handle isn't 4060 (perhaps reading the UDT info to always get the correct handle to check may be necessary).
What are your thought on this solution?

**Comment by SerafinTech** [comment]
String support is there. Here is an example:
```javascript
const {Controller, Structure} = require("st-ethernet-ip")

let c = new Controller();

(async function (){
    await c.connect('192.168.1.10');
    let tag = new Structure('TestString', c.state.tagList, 'MainProgram')

    await c.readTag(tag)

    console.log(tag.value)

    tag.value = 'Hello There!'

    await c.writeTag(tag)

    console.log(tag.value)
})();

```
I'm working on a new README
