### ISSUE TITLE
PLC disconnection recovery after reconnect

### ISSUE THREAD

**Issue by richardlrzjw** [SerafinTech/ST-node-ethernet-ip#6]
## Current Behavior
Great work guys, I can see this wonderful package. 
I am trying to use this to build a application pulling data from PLCs and dump all the data on the information screen, I don't want the information go for problem as I setup my client screen auto refresh mode (every x seconds). once I unplug ethernet cable after a certain period I got time out time out problem, I use try catch to catch the error and replace with initialization tags information  but I seem can not bypass the connection even though I saw the time out error, so basically my screen change to white question screen unless I plug the cable back. when I have SQL query running in the same situation, I could catch error and dump screen with initialization data of the tags from SQL, but this technology used for MS SQL seems not working for this package. I wonder if you have any idea can lighting up? 

error message is:
(node:7932) UnhandledPromiseRejectionWarning: Error: TIMEOUT occurred while attempting to establish TCP connection with Controller.
    at Controller.connect (C:\Users\Public\Documents\marquee_hdb\node_modules\st-ethernet-ip\src\enip\index.js:163:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Controller.connect (C:\Users\Public\Documents\marquee_hdb\node_modules\st-ethernet-ip\src\controller\index.js:191:24)

## Expected Behavior
I expect when I lost connection, the PLC connection error can be caught by try catch block and replace the tags reading with their initialization value.  

## Steps to Reproduce (for bugs only)

1.
2.
3.
4.

## Your Environment

* Package version (Use `npm list` - e.g. *1.0.6*): "st-ethernet-ip": "^2.3.2"
* Node Version (Use `node --version` - e.g. *9.8.0*):  v14.16.1
* Operating System and version: Windows server 2019 std
* Controller Type (eg 1756-L83E/B): L73, L61
* Controller Firmware (eg 30.11): Version 20, Version 16

**Comment by SerafinTech** [comment]
Can you post a code segment that shows how you are using the module?  

When you lose a connection, you are going to want to create a new controller object to create a new connection and not reuse the old controller object.

The newest version of the ST-ethernet-ip is not on NPM yet. You can install the newest version directly from Github:

`
npm install SerafinTech/ST-node-ethernet-ip
`
