### ISSUE TITLE
Incorrect expansion of Structure value with BIT_STRING typed member

### ISSUE THREAD

**Issue by pilotcam** [SerafinTech/ST-node-ethernet-ip#7]
When structure member of type BIT_STRING is expanded in the value, its type is an array of integers rather than an array of bools.

## Current Behavior
A PLC type BOOL[64] will be expanded as if it were typed DINT[2].

## Expected Behavior
A PLC type BOOL[64] should be expanded into an array of bools with length 64.

## Context
If the PLC programmer has chosen type BOOL[], there was a purposeful decision to use boolean values rather than integers.   Reading this data out of the PLC should reflect the same type.

## Steps to Reproduce (for bugs only)

1. PLC: Create a UDT with a BOOL[n], then create a tag using this type
2. EIP: `myTag = new Structure("MyTag", null, tagList);`
3. EIP: `await PLC.readTag(myTag);`
4. EIP: `console.log(myTag.value.MyBits);`

## Your Environment
* Package version (Use `npm list` - e.g. *1.0.6*): 2.3.2
* Node Version (Use `node --version` - e.g. *9.8.0*):  14.17.5
* Operating System and version: Windows 10
* Controller Type (eg 1756-L83E/B): 1756-L74
* Controller Firmware (eg 30.11): 20.19

**Comment by SerafinTech** [comment]
Merged and Published to NPM. Thanks!
